# client/stream specific properties
pulse.rules = [
    {
        matches = [
             { application.process.binary = "teams" }
             { application.process.binary = "teams-insiders" }
             { application.process.binary = "teams-for-linux" }
             { application.process.binary = "firefox" }
             { application.process.binary = "discord" }
             { application.process.binary = "legcord" }
             { application.process.binary = "vesktop" }
             { application.process.binary = "obs" }
             { application.process.binary = "steam" }
        ]
        actions = { quirks = [ block-source-volume ] }
    }
]
